export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const WINDOWINCREMENT = 'WINDOWINCREMENT';
export const TABONE = 'TABONE';
export const TABTWO = 'TABTWO';
export const TABTHREE = 'TABTHREE';
export const TABFOUR = 'TABFOUR';
export const TABFIVE = 'TABFIVE';

export const GETCOVER = 'GETCOVER';
export const TABTWOBEGIN = 'TABTWOBEGIN';
export const TABTWOSUCCESS = 'TABTWOSUCCESS';


export const WEBVIEWSHOW = 'WEBVIEWSHOW';
export const GOWEBVIEW = 'GOWEBVIEW';


export const NAVTURE = 'NAVTURE';//切换真实的环境;
export const NAVFALSE = 'NAVFALSE' ;//用临时的环境

export const WIFISTATE = 'WIFISTATE'; //wifi状态
export const UNWIFISTATE= 'UNWIFISTATE'; //非wifi状态

export const OPENDIS = 'OPENDIS';//打开交流选择的摸态框
export const CLOSEDIS = 'CLOSEDIS';//关闭交流选择的摸态框


export const OPENHEIGHTANIMA = 'OPENHEIGHTANIMA';// 选择条下拉的状态
export const CLOSEHEIGHTANIMA = 'CLOSEHEIGHTANIMA'; //选择条关闭的状态


export const UPDATECLASSINFOSUCCESS = 'UPDATECLASSINFOSUCCESS';//更新课程数据成功
export const FETCHCLASSDATASUCCESS= 'FETCHCLASSDATASUCCESS';//抓取课程数据成功



export const BEGINLOADING = 'BEGINLOADING';//加载loading
export const ENDLOADING = 'ENDLOADING'; //取消加载loading


export const STARTFETCHLOADING = 'STARTFETCHLOADING';//开启抓取数据loading
export const STOPFETCHLOADING = 'STOPFETCHLOADING';//关闭抓取数据loading


export const UPDATESKILLINFOSUCCESS = 'UPDATESKILLINFOSUCCESS';//更新技巧数据成功
export const FETCHSKILLDATASUCCESS= 'FETCHSKILLDATASUCCESS';//抓取技巧数据成功


export const UPDATEFIRSTCOMMUNIONDATASUCCESS = 'UPDATEFIRSTCOMMUNIONDATASUCCESS';//更新父类交流
export const FETCHFIRSTCOMMUNIONDATASUCCESS = 'FETCHFIRSTCOMMUNIONDATASUCCESS';//抓取父类交流


export const UPDATESECONDCOMMUNIONDATASUCCESS = 'UPDATESECONDCOMMUNIONDATASUCCESS';//更新子类数据
export const FETCHSECONDCOMMUNIONDATASUCCESS = 'FETCHSECONDCOMMUNIONDATASUCCESS';//抓取子类数据

export const CLEANSECONDCOMMUNIONDATA = 'CLEANSECONDCOMMUNIONDATA';//清除子集数据。


export const CLEANALLSKILLIMG = 'CLEANALLSKILLIMG';//清除增加的技巧图
export const ADDSKILLIMG = 'ADDSKILLIMG';//增加技巧图


export const ADDSKILLSUCCESS = 'ADDSKILLSUCCESS';//添加技巧

export const UPDATESKILLTYPESUCCESS = 'UPDATESKILLTYPESUCCESS';//技巧类型

export const CHANGESKILLTYPE = 'CHANGESKILLTYPE'; //更换技巧类型


export const UPDATECOMMUNIONTYPESUCCESS = 'UPDATECOMMUNIONTYPESUCCESS';//交流类型
export const CHANGECOMMUNIONTYPE = 'CHANGECOMMUNIONTYPE';//更新交流类型

export const ADDCOMMUNIONIMG = 'ADDCOMMUNIONIMG';//增加交流图片
export const CLEANALLCOMMUNIONIMG = 'CLEANALLCOMMUNIONIMG';//清楚增加的交流图

export const LOGINSUCCESS = 'LOGINSUCCESS';//登录成功
export const LOGOUTSUCCESS = 'LOGOUTSUCCESS';//登出
export const GETUSERSUCCESS = 'GETUSERSUCCESS';//检测到用户

export const CLOSELOGINMODAL = 'CLOSELOGINMODAL';//关闭登录窗

export const OPENLOGINMODAL = 'OPENLOGINMODAL';//打开登录窗

export const HASCOLLECT = 'HASCOLLECT';//已经收藏
export const HASNOTCOLLECT = 'HASNOTCOLLECT';//未收藏